---
connection:
  db_name: "spsm"
  db_user: "user.name"
  db_password: "user.password"
  db_port: "PostgreSQL database port (usually 5432)"
  db_host: "PostgreSQL database host"
data sources:
  # Cleaned, enriched dataset of Condor data source
  condor: "FILE.csv"

  # Dataset of manually completed URLs from Condor dataset
  completed urls: "FILE.csv"

  # Cleaned, enriched dataset of Science Feedback data source
  science feedback: "FILE.csv"

  # Cleaned, enriched dataset of De Facto data source
  de facto: "FILE.json"

  # Dataset of HTML titles, YouTube titles, WebArchive titles, concatenated Condor share titles
  supplemental titles: "FILE.csv"

  # Dataset of HTML titles, YouTube titles, WebArchive titles, concatenated Condor share titles
  query titles: "FILE.csv"

  # Dataset of all the URLs with their corresponding tweet-search version
  url titles: "FILE.csv"
