---
connection:
  db_name: "spsm"
  db_user: "user.name"
  db_password: "user.password"
  db_port: "PostgreSQL database port (usually 5432)"
  db_host: "PostgreSQL database host"
data sources:
  condor: ""
  completed urls: ""
  science feedback: ""
  de facto: ""
  supplemental titles: ""
  searchable titles and urls: ""
